title: my-ggott blog
description: my-ggott language 로 번역한 자료를 모아놓았어요.

url: https://gheejeon.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: GHeeJeon
  twitter:
  facebook:
  email: jhjeon_99@naver.com
  linkedin:

google_analytics: "UA-58263416-1"

disqus:
    shortname: GHeeJeon
