# Site settings
title: my-ggott blog
email: jhjeon_99@naver.com
description: > # this means to ignore newlines until "baseurl:"
  ㅇ0ㅇ 마이깟!! 배운 내용을 my-ggott language 로 번역해 둔 곳입니다.
baseurl: # the subpath of your site, e.g. /blog/
url: # the base hostname & protocol for your site
github_username: GHeeJeon

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


